Removed java from package.

diff --git a/techniclauncher b/techniclauncher
--- a/techniclauncher
+++ b/techniclauncher
@@ -1,7 +1,26 @@
 #/bin/sh
 
-JAVA_HOME=/opt/TechnicLauncher/java
+if [ -e /opt/java ]; then
+	JAVA_HOME=/opt/java
+else
+	for j in /opt/jdk*/bin/java /opt/jre*/bin/java; do
+		if [ -f $j ]; then
+			JAVA_HOME=$(dirname $(dirname $j))
+			break;
+		fi
+	done
+
+	echo "Note: No java installs found in opt"
+	echo "Note: Fallback to system java"
+fi
+
+if [ -z $JAVA_HOME ]; then
+	echo "Error: unable to find a java install."
+	exit 1
+fi
+
+echo "Using java in $JAVA_HOME"
 JRE_HOME=$JAVA_HOME
-PATH="/opt/TechnicLauncher/java/bin:$PATH"
+PATH="$JAVA_HOME/java/bin:$PATH"
 
 java -jar /opt/TechnicLauncher/jar/TechnicLauncher.jar
